### PR TITLE
Refactor https://github.com/apache/beam/pull/30847

### PR DESCRIPTION
**Pull request by damondouglas**
Instead of commenting on https://github.com/apache/beam/pull/30847, I am submitting a PR of `utility_cluster`. I tested both .test-infra/terraform/google-cloud-platform/google-kubernetes-engine and .test-infra/kafka/strimzi and a new Google Cloud project. I was able to provision both the GKE cluster and the strimzi helm chart, but I didn't see any further Kubernetes artifacts other than the operator deployment. Listed below is what this PR suggests. Below is a list of what remains.

- Replaces .test-infra/kafka/strimzi with what you had as strimzi-operator
- Simplifies README instructions
- Moves default variable values to `common.tfvars` or start `tfvars` such as .test-infra/terraform/google-cloud-platform/google-kubernetes-engine/us-central1.apache-beam-testing.tfvars
- Fixes gcloud command output

# What remains

1) It wasn't clear from the strimzi helm chart documentation what happens after the helm chart is applied. I only saw a strimzi operator deployment and no other Kubernetes artifacts such as a service, etc.
2) I left a TODO comment in .test-infra/kafka/strimzi/README.md. See .test-infra/kafka/bitnami/README.md as an example for how to help people connect to the Kafka cluster. I hope we can see the same for the strimzi README.
3) I hope we will see an internally load balanced Service associated with the Kafka cluster. It wasn't clear if this was available from the helm documentation. See .test-infra/kafka/bitnami/kafka.tf for an example of how I added the load balancer annotations so that it is internally load balanced in GKE.

### CODE REVIEW

**Comment by volatilemolotov** [comment]
Think that its not clear what [#30847](https://github.com/apache/beam/pull/30847) tries to do. Its purpose is to have terraform for a cluster that will serve as part of the test infra for all the needed utilities on for the workflows in apache/beam repo.In this case we start with kafka which should use terraform to build a cluster and then install a strimzi operator chart. The workflow then should use the kafka kustomization already present in the repo. 

With that it clarifies couple of remains:
>> It wasn't clear from the strimzi helm chart documentation what happens after the helm chart is applied. I only saw a
>> strimzi operator deployment and no other Kubernetes artifacts such as a service, etc. 
The purpose was to install a operator on the cluster and then test can use }/.test-infra/kafka/strimzi/02-kafka-persistent/overlays/gke-internal-load-balanced to instantiate its own kafka for the test purpose

>> I hope we will see an internally load balanced Service associated with the Kafka cluster. It wasn't clear if this was 
>>vailable from the helm documentation. See .test-infra/kafka/bitnami/kafka.tf for an example of how I added the load 
>>balancer annotations so that it is internally load balanced in GKE. 
Given that we are to reuse the customization the balancing will be internal

Also note that:
- we should not remove kafka persistent kustomization files from the repo as its intended to use them in workflows.
- We should not also remove operator kustomization as perhaps in manual setups people still can use that
- the common tfvars in strimzi kafka terrraform - should we have it - The purpose of this terraform is to install strimzi to apache-beam-testing project to be used by the workflows there
- Why is strimzi terraform moved to .test-infra/kafka. This terraform only installs the operator for the cluster and it makes more sense to keep it in terrafrom folder, close to the tfvars of its cluster
- Why are tfvars files for clusters named by regions eg. region.apache-beam-testing.tfvars . We are building clusters not regions so it makes sense to have by cluster name. beam-utility.apache-beam-testing.tfvars in my example

**Comment by damondouglas** [comment]
> we should not remove kafka persistent kustomization files from the repo as its intended to use them in workflows.

This makes sense, I agree.

> We should not also remove operator kustomization as perhaps in manual setups people still can use that

I think we should either use one or the other. I prefer the helm terraform solution; it seems cleaner.

> the common tfvars in strimzi kafka terrraform - should we have it 

I personally prefer to default using `tfvars` instead of using variable defaults. Individuals are more likely to notice a variable this way and are not suprised.

> Why is strimzi terraform moved to .test-infra/kafka

https://github.com/akvelon/beam/tree/utility_cluster places it under google_cloud_platform. I'd argue it makes more sense under kafka. The compromise is to just place it directly under terraform instead of google_cloud_platform.

> This terraform only installs the operator for the cluster and it makes more sense to keep it in terrafrom folder, close to the tfvars of its cluster

The tfvars should be in the same directory as the module to which it applies. This convention is understood by IDEs that will autocomplete the variables when editing tfvars files.

> Why are tfvars files for clusters named by regions eg. region.apache-beam-testing.tfvars . We are building clusters not regions so it makes sense to have by cluster name. beam-utility.apache-beam-testing.tfvars in my example

Auto pilot GKE cluster is isolated by region. The two region tfvars files that already exist are helpful starters because the subnetwork name is different between the two regions.

**Comment by volatilemolotov** [comment]
Ok so, 
> I think we should either use one or the other. I prefer the helm terraform solution; it seems cleaner.

Terraform it is then, it is cleaner.

> The tfvars should be in the same directory as the module to which it applies. This convention is understood by IDEs that will >autocomplete the variables when editing tfvars files.

Yeah, makes sense.

> Auto pilot GKE cluster is isolated by region. The two region tfvars files that already exist are helpful starters because the > subnetwork name is different between the two regions.

Also makes sense. What is unclear is can i later upload the `utility-beam.apache-beam-testing.tfvar` alongside these starter files. I want it source controlled.


Rest i agree without issue. Let me know when you merge changes so i can figure out the change how backends are handled

**Comment by damondouglas** [comment]
> Also makes sense. What is unclear is can i later upload the utility-beam.apache-beam-testing.tfvar alongside these starter files. I want it source controlled.

Yes, please version control the `tfvars` and note that the expected format is `<cluster-id-prefix>.<region>.<project>.tfvars`. I would expect the the `cluster-id-prefix` to be something more specific that `utility-beam` but rather `strimzi` or `strimzi-kafka`.

> Let me know when you merge changes so i can figure out the change how backends are handled

Will target updating my changes tomorrow Thursday PST time. Thank you for responding and being open to my suggestions.

**Comment by volatilemolotov** [comment]
Just regarding the name: 

Idea is that not only kafka operator is there but perhaps more stuff. Perhaps we can find operators or use exiting manifests for hadoop, postgres, mongo, rabbitmq etc., whatever workflows need

**Pull request closed without merging**
